<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<title>{block name=title}Default Title{/block}</title>
{*	<script src="//www.google.com/jsapi"></script>
	<script>
		google.load('jquery', '1.8.2');
	</script>
*}	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	{block name=head}{/block}
</head>
{* The div#container is for Bootstrap *}
<body><div class="container">{block name=body}Default Body{/block}i</div></body>
</html>
