<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<title>{block name=title}Default Title{/block}</title>
{*	<script src="//www.google.com/jsapi"></script>
	<script>
		google.load('jquery', '1.8.2');
	</script>
*}	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	{block name=head}{/block}
</head>
<body>{block name=body}Default Body{/block}</body>
</html>